import clsx from "clsx";
import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

// Font files can be colocated inside of `pages`
const helvetica = localFont({
  src: [
    {
      path: "./fonts/HelveticaNeue-thin.ttf",
      weight: "200",
      style: "thin",
    },
    {
      path: "./fonts/HelveticaNeue-Light.woff2",
      weight: "300",
      style: "normal",
    },
    {
      path: "./fonts/HelveticaNeue-LightItalic.woff2",
      weight: "300",
      style: "italic",
    },
    {
      path: "./fonts/HelveticaNeue.woff2",
      weight: "400",
      style: "normal",
    },
    {
      path: "./fonts/HelveticaNeue-Italic.woff2",
      weight: "400",
      style: "italic",
    },
    {
      path: "./fonts/HelveticaNeue-Bold.woff2",
      weight: "700",
      style: "normal",
    },
    {
      path: "./fonts/HelveticaNeue-BoldItalic.woff2",
      weight: "700",
      style: "italic",
    },
  ],
  variable: "--font-helvetica",
});

const BetterVCR = localFont({
  src: [
    {
      path: "./fonts/BetterVCR.ttf",
      weight: "400",

      style: "normal",
    },
  ],
  adjustFontFallback: false,
  variable: "--font-betterVCR",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={clsx(
        helvetica.variable,
        BetterVCR.variable,
        "h-full antialiased",
      )}
    >
      <body className="bg-[#090909]">{children}</body>
    </html>
  );
}
